### ISSUE TITLE
Docs improvement - readthedocs, sphinx and docs from code

### ISSUE THREAD

**Issue by allburov** [devopshq/tfs#17]
For now, lib have many usefull API inside code, but have not any docs about it. All docs are manual created and separated from code
To improvement docs, we need:

- [x] Convert all static MD to RST docs
- [x] Generate dynamic docs (through sphinx) and 
- [x] Publish docs to readthedocs
- [x]  Add more docstring with example to code

**Comment by Boltyk** [comment]
#56

**Comment by allburov** [comment]
@Boltyk thanks for working on this issue! 
Documentation hosted on https://devopshq.github.io/tfs/
