### ISSUE TITLE
class-by-uri refactoring

### ISSUE THREAD

**Issue by allburov** [devopshq/tfs#18]
Now, object class pass in method like this:
```python
self.get_tfs_object('tfvc/changesets', payload=payload, object_class=Changeset)
```
but better way is use map like jira: https://github.com/pycontribs/jira/blob/develop/jira/resources.py#L922

**Comment by Boltyk** [comment]
https://github.com/pycontribs/jira/blob/develop/jira/resources.py#L922 is 404

**Comment by allburov** [comment]
Develop brach was removed :(

master https://github.com/pycontribs/jira/blob/master/jira/resources.py#L1034, `resource_class_map`

Main idea is if we call `get_tfs_object('some/path')` without object_class, object class must be autodetected by some map.

**Comment by Boltyk** [comment]
#65

**Comment by allburov** [comment]
@Boltyk thanks!
