### ISSUE TITLE
Simplify querying for just one changeset

### ISSUE THREAD

**Issue by fuzzmz** [devopshq/tfs#26]
Currently the only way to get information for a specific changeset is to use the same value in the `from_` and `to_` fields, for example `changesets = client.get_changesets(from_=601859, to_=601859)`.

I propose updating the `get_changesets` method so that if it is called with an ID then it automatically parses that as querying for one changeset. What is mean is that calling `get_changesets(601859)` would be equivalent to `get_changesets(from_=601859, to_=601859)`.

**Comment by allburov** [comment]
Fixed in `pip install dohq-tfs==1.0.96`

**Comment by allburov** [comment]
@fuzzmz thanks for contribution!
