### ISSUE TITLE
WIQL: add timePrecision parameter to request

### ISSUE THREAD

**Issue by RealOnix** [devopshq/tfs#49]
Can you add **timePrecision** boolean parameter when running WIQL query?
Example:
POST https://dev.azure.com/{organization}/{project}/{team}/_apis/wit/wiql?timePrecision={timePrecision}&api-version=1.0

**Comment by SAnCherepan** [comment]
@RealOnix, when my changes are merged to masted, you will be able to add any URI parameters via python dictionary (see [updated docs in custom branch](https://github.com/devopshq/tfs/tree/docs/rest-client#run-wiql)).
