### ISSUE TITLE
support tempQueryId in queries?

### ISSUE THREAD

**Issue by axtrace** [devopshq/tfs#53]
Hi! 
I met this case. I have a link on query which looks like `https://server/tfs/DefaultCollection/project/_workitems?_a=query&tempQueryId=7d123e4af-f52e-4c0d-a220-b5cceffa8f5e`

As I can see, only 'path' of query is available for getting workitems via api.
But in this link there no path.

Could you add an oppotunity to get workitems and other query result by QueryId?

**Comment by SAnCherepan** [comment]
@axtrace, thank you for your question!

Have you tried using this GUID as path?
AFAIK, something like
`query = client.run_query('7d123e4af-f52e-4c0d-a220-b5cceffa8f5e')`
should work just fine as long as that query is accessible via a link like this:
`https://server/tfs/DefaultCollection/project/_apis/wit/queries/7d123e4af-f52e-4c0d-a220-b5cceffa8f5e`

Im going to update our docs to clarify that GUID can be used as path aswell.

**Comment by axtrace** [comment]
Hi! Thank you for you answer and for updating docs!

I've tried this approach and it failed in my tfs context.

But I suggest it depens on my environment more than of your lib
