### ISSUE TITLE
Returned HTTP 403 Forbidden error when create_workitem called

### ISSUE THREAD

**Issue by ihar512** [devopshq/tfs#62]
Hi. I have two TFS, TFS1 and TFS2. I am able to create a bug by calling create_workitem on TFS1, but getting error 403 forbidden when I tried to do the same on TFS2. Both personal access tokens have full access. Any idea of why this is happening? Thanks.

**Comment by Boltyk** [comment]
@ihar512 can you share some code examples?

**Comment by ihar512** [comment]
@Boltyk this problem have been resolved. Thanks.

**Comment by allburov** [comment]
@ihar512 could you give us reason why access failed? It will help for someone

**Comment by ihar512** [comment]
@allburov It failed because the TFS that did not work was TFS 2012 which does not support by the API.
