### ISSUE TITLE
Retrieve test results?

### ISSUE THREAD

**Issue by pbissert** [devopshq/tfs#63]
Can results for a given test case be retrieved using this library?

**Comment by allburov** [comment]
@pbissert all functions are described in the documentation https://devopshq.github.io/tfs/

If you have a special case - describe in more detail what you want to receive with links to TFS documentation

**Comment by pbissert** [comment]
For example, test case work items can have results from test runs. There is documentation in the Azure API (https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results?view=azure-devops-rest-5.0). I was wondering if any of these are planned to be added to this library?
