### ISSUE TITLE
Support 2.7

### ISSUE THREAD

**Issue by tejeswarak** [devopshq/tfs#64]
We have python 2.7 where we have our code base. But this tfs project supports 3.4.
Is there anyway that supports 2.7?

**Comment by allburov** [comment]
@tejeswarak I think it's possible, but we need help.

**Comment by Boltyk** [comment]
Having that "2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support." [PEP 373 -- Python 2.7 Release Schedule](https://www.python.org/dev/peps/pep-0373/) is it still worth the efforts?

**Comment by allburov** [comment]
Let's just update python environment!
