### ISSUE TITLE
Cannot get "System.Tags" data for Work Items

### ISSUE THREAD

**Issue by TrevorDBrown** [devopshq/tfs#66]
When trying to use the Work Item attribute "Tags" (or "System.Tags"), I get the following error:

```
Traceback (most recent call last):
  File ".\get-tfs-data.py", line 35, in <module>
    main()
  File ".\get-tfs-data.py", line 32, in main
    parseTFSQueryData(client, readyToGroomDesign)
  File ".\get-tfs-data.py", line 22, in parseTFSQueryData
    print("%s, %s, %s, %s, %s, %s" % (workitem['Id'], workitem['WorkItemType'], workitem['System.Title'], workitem['AssignedTo'], workitem['State'], workitem['tags']))
  File "C:\Python37\lib\site-packages\tfs\resources.py", line 107, in __getitem__
    return self.fields[key]
  File "C:\Python37\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'system.tags'
```

I've verified other attributes work as expected (i.e. Title (System.Title))

**Comment by Boltyk** [comment]
Do you have any tags on this work item?

**Comment by TrevorDBrown** [comment]
Hello, @Boltyk,

The instance above did not. I tried a work item with at least one tag, and it worked. Sorry for not testing that beforehand.

So, I assume it'll always fail if the particular work item does not have the specified key-value pair?

**Comment by Boltyk** [comment]
Looks like a valid bug for me.
Thanks @TrevorDBrown

**Comment by TrevorDBrown** [comment]
Tested the develop branch with the changes. Worked great! Thank you, @Boltyk!
