### ISSUE TITLE
401 error with Django

### ISSUE THREAD

**Issue by manikyab** [devopshq/tfs#78]
When the workitem or changest is accessed using Django app using HTTP_NEGOTIATE_SSPI.HttpNegotiateAuth as authentication it is giving error of 401 as invalid

**Comment by allburov** [comment]
Django in the TFS library's issue o_O 
@manikyab What infrastructure do you have: TFS version, how do django communicate with TFS? Could you give us some peace of code to reproduce this issue

**Comment by manikyab** [comment]
I am using TFS 2017 with windows authentication only and trying to access a python script which is connecting to TFS using HTTPRequestNegotiate as auth_type
The server is IIS10.0 with CGI and windows authentication enable in it
Python3.7
Django 2.2
TFS 2017 version
IIS 10.0

**Comment by ondrno** [comment]
@manikyab : Can you please share the relevant pieces of the source code? This would help to understand your issue.
