### ISSUE TITLE
This seems to work only with basic authentication enabled

### ISSUE THREAD

**Issue by PeteW** [devopshq/tfs#8]
Default on-prem installations of TFS 2015/2017 dont enable basic auth. For many (myself included) requesting enabling of basic auth is a cross-departmental barrier. Suggest considering support for NTLM auth and/or the personal access token.

I dont have time to work on this (yet) but it would seem for the access token you would have something like:
`curl -u {username}[:{personalaccesstoken}] https://{server}:8080/DefaultCollection/_apis/projects?api-version=2.0`
or adding the header:
`Authorization: Basic <BASE64 personalaccesstoken>`
According to the [API docs](https://www.visualstudio.com/en-us/docs/integrate/get-started/rest/basics#tfs)

My particular site of interest does not have basic auth enabled however [TFS-CLI](https://github.com/Microsoft/tfs-cli/) does work using personal access tokens thus proving this is possible to accomplish without basic-auth.

**Comment by allburov** [comment]
Hello, thank you for your suggestion!
For now, we can implement and test only **NTLM** auth, we have only 2015 Instance, it isn't support personalaccesstoken
Somebody else can test this library with access token and create pull requests :)

```python
# DEFAULT - Use HTTP Basic Auth
client = TFSAPI("https://tfs.tfs.ru/tfs/", user=user, password=password)

# Use NTLM authentication
from requests_ntlm import HttpNtlmAuth
client = TFSAPI("https://tfs.tfs.ru/tfs/", user=user, password=password, auth_type=HttpNtlmAuth)
```
