### ISSUE TITLE
name 'tfs' is not defined

### ISSUE THREAD

**Issue by Danecek1** [devopshq/tfs#81]
Hi,
I installed python 3.8 through chocolatey on win10. Then in cmder I ran simple script but it fails at the 1st line: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tfs' is not defined
```

First line is:
`from tfs import TFSAPI`

Do anyone has any idea what to do, please?
Thanks!

**Comment by SAnCherepan** [comment]
@Danecek1, make sure you have the `dohq-tfs` package installed for the python that is used to run the script.

If you only have one python version installed then run `pip install dohq-tfs` in you cmd.
If you have multiple python versions on the same machine, use `<your_python_executor> -mpip instal dohq-tfs` instead.

Let me know if it helps.

**Comment by Danecek1** [comment]
@SAnCherepan Thanks a lot, I have 2 versions - 2.7 and 3.8. I did 
`python -mpip instal dohq-tfs` for python 2.7, but I need for 3.8 so I ran:
`python3 -mpip install dohq-tfs` but this command does completely nothing. Even if I try run easy script with python3 (which just prints "hello"), it doesnt nothing. 

Thanks a lot.

**Comment by Danecek1** [comment]
@SAnCherepan I resolved it. Dont know why, but I had to install python through Windows Store directly and it works. Before, I installed it through chocolatey...

Thanks again, Daniel

**Comment by SAnCherepan** [comment]
@Danecek1 always welcome!
